<a href="https://colab.research.google.com/github/manikanta741/Data-Science/blob/main/Numpy%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#pandas

"""Key Features of Pandas

 DataFrame & Series – Efficient tabular data structures
 Data Cleaning – Handling missing values, duplicates, etc.
 Data Transformation – Filtering, sorting, merging, and aggregation
 Statistical Analysis – Summary statistics, groupby, pivot tables
 Integration – Works well with NumPy, Matplotlib, Scikit-learn, and databases"""



In [4]:
#series
import pandas as pd
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)


0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
#dataframe
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)


In [ ]:
#reading data
df = pd.read_csv("data.csv")  # Read CSV
df = pd.read_excel("data.xlsx")  # Read Excel
df = pd.read_sql("SELECT * FROM table", connection)  # Read SQL


In [ ]:
df.head()    # First 5 rows
df.tail()    # Last 5 rows
df.info()    # Summary of DataFrame
df.describe()  # Summary statistics


In [ ]:
#filtering
df[df["Age"] > 30]  # Filter rows
df.loc[0, "Name"]  # Access specific row & column
df.iloc[1:3, 0:2]  # Access using index positions


In [ ]:
#sorting and aggregation
df.sort_values("Age", ascending=False)  # Sort by Age
df.groupby("Category").mean()  # Group and compute mean


In [7]:
#merging
df1.merge(df2, on="ID", how="inner")  # SQL-like joins


In [9]:
#numpy
#1-d array
import pandas as pd
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [10]:
#2-d array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)


[[1 2 3]
 [4 5 6]]


In [11]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print(np.zeros((2, 3)))   # 2x3 array of zeros


[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(np.ones((3, 3)))   # 3x3 array of ones



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
np.full((2, 2), 7) # 2x2 array filled with 7


array([[7, 7],
       [7, 7]])

In [16]:
np.eye(3)          # Identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(3, 3) # Random values between 0 and 1

array([[0.05316992, 0.95428158, 0.41220352],
       [0.96419991, 0.29833481, 0.26044564],
       [0.38974394, 0.1749979 , 0.52520242]])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication
print(a ** 2) # Element-wise power


[5 7 9]
[ 4 10 18]
[1 4 9]


In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A @ B)  # Matrix multiplication
print(np.dot(A, B))  # Alternative for dot product
print(np.linalg.inv(A))  # Inverse of a matrix


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
#indexing slicing
arr = np.array([[10, 20, 30], [40, 50, 60]])

print(arr[1, 2])  # Access row 1, column 2 (60)
print(arr[:, 1])  # Get second column
print(arr[0, :])  # Get first row
print(arr[0:2, 1:3])  # Get sub-array


60
[20 50]
[10 20 30]
[[20 30]
 [50 60]]


In [23]:
np.mean(arr)   # Mean
np.median(arr) # Median
np.std(arr)    # Standard deviation
np.sum(arr)    # Sum of all elements
np.max(arr)    # Maximum value
np.min(arr)    # Minimum value


10

In [25]:
dat=[1,2,1,2,1,1,1,12,2,3]
print(np.bincount(dat).argmax())

1


In [ ]:
#scipy
"""
scipy.linalg	Linear algebra (matrix operations, determinants, inverse)
scipy.optimize	Optimization (minimization, root finding, curve fitting)
scipy.stats	Statistical functions (distributions, hypothesis testing)
scipy.signal	Signal processing (filtering, FFT, wavelets)
scipy.spatial	Spatial data structures (KD trees, distance metrics)
scipy.integrate	Integration (solving ODEs, numerical integration)
scipy.interpolate	Interpolation (spline fitting, polynomial interpolation)
"""

In [37]:
#mode
from scipy import stats
print(stats.mode(data))

ModeResult(mode=10, count=1)


In [26]:
from scipy.linalg import inv, det

A = np.array([[1, 2], [3, 4]])
print(inv(A))  # Inverse of A
print(det(A))  # Determinant of A


[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0


In [33]:
#optimisation
from scipy.optimize import minimize

def func(x):
    return x**2 + 3*x + 2  # Quadratic function

result = minimize(func, x0=0)  # Minimize function starting at x0=0
print(result.x)  # Optimal x value


[-1.50000001]


In [34]:
#Solving Equations (Root Finding)
from scipy.optimize import fsolve

def equation(x):
    return x**2 - 4  # Solving x² - 4 = 0

root = fsolve(equation, x0=2)  # Initial guess x0=2
print(root)  # Output: [2, -2]


[2.]


In [35]:
#special functions
#Gamma Function:
"""Probability Theory: The gamma function is used in probability
 theory to model the distribution of random variables, such
 as the exponential distribution and the gamma distribution."""
from scipy import special
import numpy as np

# Calculate the gamma function
x = np.array([1, 2, 3, 4, 5])
gamma_x = special.gamma(x)
print(gamma_x)



[ 1.  1.  2.  6. 24.]


In [ ]:
## Calculate the error function
 """Probability Theory: The error function is used in probability
 theory to model the distribution of random variables,
  such as the normal distribution and the logistic distribution."""

x = np.array([1, 2, 3, 4, 5])
erf_x = special.erf(x)
print(erf_x)
